### ISSUE TITLE
 Inquiry About Hyperparameter Settings in CAT-SAM Training Script

### ISSUE THREAD

**Issue by kerongYan** [weihao1115/cat-sam#3] opened 2024-08-10 02:36 UTC
Dear Author,

I am honored to have come across your paper titled "CAT-SAM: Conditional Tuning for Few-Shot Adaptation of Segment Anything Model" published in ECCV. Due to the outstanding segmentation performance demonstrated, I am attempting to reproduce the experimental results from your paper.

Following the training script you uploaded to GitHub last month, I have trained the CAT-SAM-A model using a 1-shot approach on the Kvasir and SBU datasets, based on the ViT-L pre-trained model. I set the batch size to 1, but unfortunately, the results I obtained are less satisfactory. On the Kvasir dataset, I achieved a maximum mIOU of 82.63%, which is significantly lower than the 85.4% reported in your paper. Similarly, on the SBU dataset, the best result I obtained was 78.26%, which also falls short of the 81.9% mentioned in the paper.

I would like to inquire about the details of your training process. Could you please provide some guidance? If possible, I would greatly appreciate it if you could share the training script used to produce the results in your paper. I look forward to your response and thank you very much for your assistance.

**Comment by weihao1115** [comment] 2024-08-10 14:54
Hi @kerongYan ,

Thank you for your interest in our work!

During our experiments, we found randomness largely due to bilinear interpolation. We repeated multiple experiments in a single setting and reported the median results. Could you please provide the detailed experimental environments? Then, we can think of how to reproduce your results and check what happened.

Best regards,

**Comment by weihao1115** [comment] 2024-08-10 14:55
Hi @kerongYan ,

Thank you for your interest in our work!

During our experiments, we found randomness largely due to bilinear interpolation. We repeated multiple experiments and reported the median results. Could you please provide the detailed experimental environments? Then, we can think of how to reproduce your results and check what happened.

Best regards,

**Comment by kerongYan** [comment] 2024-08-13 03:07
Dear Author,

Regarding your response, "During our experiments, we found randomness largely due to bilinear interpolation," I have reviewed the data augmentation section of the training script:

if worker_args.cat_type == 'cat-t' and worker_args.dataset in ['kvasir', 'sbu']:
    transforms = [VerticalFlip(p=0.5), HorizontalFlip(p=0.5)]
else:
    transforms = [VerticalFlip(p=0.5), HorizontalFlip(p=0.5), RandomCrop(scale=[0.1, 1.0], p=1.0)]
However, I did not find any operations related to bilinear interpolation. Could you please provide further guidance on this matter?

Thank you.

**Comment by weihao1115** [comment] 2024-08-13 11:58
Please refer to [here](https://github.com/weihao1115/cat-sam/blob/060632cd82efa5430e3a3870f26947b32af4cbbb/cat_sam/models/modeling.py#L387). It is also important to note that although we mentioned that changing to nearest can reduce the randomness, it will lead to decreased performance due to its original design compared with bilinear interpolation.

Best regards,

**Comment by weihao1115** [comment] 2024-08-21 15:09
Because there have been no more responses, I am closing this issue here. Please feel free to re-open it.

Best regards,

**Closed as completed by weihao1115** 2024-08-21 15:09 UTC
